dist: trusty
sudo: true

language: node_js
node_js:
    - "8"

cache:
  directories:
    - "node_modules"

script:
    - npm install grunt-cli bower && cd omega-build && npm run deps && npm run dev && grunt

notifications:
  email:
    on_success: never
    on_failure: never
